name: Upload Assets to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
  upload-win-assets-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download WIN release assets
        uses: duhow/download-github-release-assets@v1
        with:
          repository: everdome-io/event-spaces-launcher
          release-id: latest
          files: Everdome-Spaces-Launcher-Setup-${{ inputs.version }}.exe
          target: Everdome-Spaces-Launcher-Setup.exe

      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: Everdome-Spaces-Launcher-Setup.exe
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.UPLOAD_AWS_S3_BUCKET }}
          S3_KEY: Everdome-Spaces-Launcher-Setup.exe
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

  upload-mac-assets-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download MAC release assets
        uses: duhow/download-github-release-assets@v1
        with:
          repository: everdome-io/event-spaces-launcher
          release-id: latest
          files: Everdome-Spaces-Launcher-${{ inputs.version }}.dmg
          target: Everdome-Spaces-Launcher.dmg

      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: Everdome-Spaces-Launcher.dmg
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.UPLOAD_AWS_S3_BUCKET }}
          S3_KEY: Everdome-Spaces-Launcher.dmg
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

  create-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON file
        run: |
          echo '{ "latest": "${{ inputs.version }}" }' > launcher-version.json

      - name: Upload json file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: launcher-version.json
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: launcher-version.json
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
